config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show]
  resources :perfumes

  
  root 'tweets#top'  
  get 'hello/index' => 'hello#index'
  # get 'tweets/:id' => 'tweets#show',as: 'tweet'

  # root 'hello#index'
 
  get    'tweets/top'      => 'tweets#top'
 
  
  resources :tweets do
  resources :likes, only: [:create, :destroy]
  
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :tweet
  belongs_to :user
  validates_uniqueness_of :tweet_id, scope: :user_id
end

app/models/perfume.rb
class Perfume < ApplicationRecord
end

app/models/tag.rb
class Tag < ApplicationRecord
  validates :name, presence: true
  has_many :tweet_tag_relations, dependent: :destroy
  has_many :tweets, through: :tweet_tag_relations, dependent: :destroy
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  mount_uploader :image, ImageUploader
  has_one_attached :image
  belongs_to :user
  
    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user
  has_many :tweet_tag_relations, dependent: :destroy
  has_many :tags, through: :tweet_tag_relations, dependent: :destroy
end

app/models/tweet_tag_relation.rb
class TweetTagRelation < ApplicationRecord
  belongs_to :tweet
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tweets, dependent: :destroy 
  has_many :likes, dependent: :destroy
  has_many :liked_tweets, through: :likes, source: :tweet
  def already_liked?(tweet)
    self.likes.exists?(tweet_id: tweet.id)
  end
  validates :name, presence: true 
  validates :profile, length: { maximum: 200 } 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile])
  end
end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    like = current_user.likes.create(tweet_id: params[:tweet_id]) 
    redirect_back(fallback_location: root_path)
  end

  def destroy
    like = Like.find_by(tweet_id: params[:tweet_id], user_id: current_user.id)
    like.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/perfumes_controller.rb
class PerfumesController < ApplicationController
  def index
    age = params[:age].to_i
    sex = params[:sex].to_i
    glasses = params[:glasses].to_i
    paper = params[:paper].to_i
    sleep = params[:sleep].to_i
    angry = params[:angry].to_i
    down = params[:down].to_i
    eye = params[:eye].to_i
    tired = params[:tired].to_i
    hand = params[:hand].to_i 
    
    # age = params[:age]
        # sex = params[:sex]
        # glasses = params[:glasses]
        # paper =params[:paper]
        # sleep =params[:sleep]
        # angry =params[:angry]
        # down =params[:down]
        # eye = params[:eye]
        # tired =params[:tired]
        # hand =params[:hand]

        @result = age + sex + glasses + paper + sleep + angry + down + eye + tired + hand
        @perfumes = Perfume.all
    # end
 
  end


  def top
    @perfume = Perfume.new
  end
  def new
    @perfume = Perfume.new
  end

  def show
    @perfume = Perfume.find_by(id: params[:id])
  end

  def create
    @perfume = Perfume.new(perfume_params)
    params[:perfume][:question] ? @perfume.question = params[:perfume][:question].join("") : false
    if @perfume.save
        flash[:notice] = "診断が完了しました"
        redirect_to perfume_path(@perfume.id)
    else
        redirect_to :action => "new"
    end
  end

private
  def perfume_params
      params.require(:perfume).permit(:id, question: [])
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user! 
  def top
  
    
  end
  def index
  
    @tweets = Tweet.where(release:1).order(id: "DESC")
  
    if params[:search] == nil
      @tweets= Tweet.all
    elsif params[:search] == ''
      @tweets= Tweet.all
    else
      @tweets = Tweet.where("title LIKE ? ",'%' + params[:search] + '%')
  
    end


    @tweets=Tweet.all
    if params[:tag_ids]
      @tweets = []
      params[:tag_ids].each do |key, value|
          if value == "1"
              tag_tweets = Tag.find_by(name: key).tweets
              @tweets = @tweets.empty? ? tag_tweets : @tweets & tag_tweets
          end
        end
        @tweets = @tweets.page(params[:page]).per(3)
    end
  end

  
  def new
    @tweet = Tweet.new
    if params[:tag]
      Tag.create(name: params[:tag])
    end
  end
  def create
    tweet = Tweet.new(tweet_params)
   tweet.user_id = current_user.id 
    if tweet.save
      redirect_to :action => "index"
    else
      redirect_to :action => "new"
    end
  end

   

  # tweet = Tweet.new(tweet_params)
  
  # if tweet.save
  #   redirect_to :action => "index"
  #   if params[:tag_ids]
  #     @tweets = []
  #     params[:tag_ids].each do |key, value|
  #       if value == "1"
  #         tag_tweets = Tag.find_by(name: key).tweets
  #         @tweets = @tweets.empty? ? tag_tweets : @tweets & tag_tweets
  #       end
  #     end
  #   end
  # else
  #   redirect_to :action => "new"
  # end

  

 def show
  @tweet = Tweet.find(params[:id])
 end
 
 def edit
  @tweet = Tweet.find(params[:id])
 end
 def update
  tweet = Tweet.find(params[:id])
  if tweet.update(tweet_params)
    redirect_to :action => "show", :id => tweet.id
  else
    redirect_to :action => "new"
  end
 end

 def destroy
  tweet = Tweet.find(params[:id])
  tweet.destroy
  redirect_to action: :index
 end
 
 private
 def tweet_params
    params.require(:tweet).permit(:title, :image , :release, tag_ids: [] ) 
 end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id]) 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/hellos_helper.rb
module HellosHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/tweet_helper.rb
module TweetHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/hello/index.html.erb
<%= link_to "ログイン", tweets_path %>
<%= link_to "新規登録", new_user_registration_path %>

app/views/hellos/edit.html.erb
<%= form_for @hello do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, :size => 140 %> 
  <%= f.submit "編集する" %>
<% end %>

app/views/hellos/index.html.erb
<h1>趣味について</h1>
<h3>Tweet一覧</h3>
<%= link_to "新規投稿へ", new_hellos_path %>
<div class="hellos-container">
  <% @hellos.each do |t| %>
    <div class="hello">
    <%= form_tag({controller:"hellos",action:"index"}, method: :get) do %>
      <%= text_field_tag :tag %>
      <%= submit_tag 'タグを追加' %>
    <% end %>
    <% Tag.all.each do |t| %>
        <%= image_tag t.image_url, size: "250x200" if t.image? %>
         <li><%= check_box :tag_ids, t.name %><%= t.name %></li>
       <% end %>
    <%= submit_tag '検索' %>
    <% end %>
      <%= t.title %>
      <%= t.created_at %>
      <%= link_to "詳細へ", hello_path(t.id) %>
      <%= link_to "編集する", edit_hello_path(t.id) %>
      <%= button_to "削除する", hello_path(t.id), method: :delete %>
    </div>
    <% end %>
</div>

app/views/hellos/new.html.erb
h1>趣味について</h1>
<h3>新規Tweet</h3>
<%= form_for @hello do |f| %>
 <div class='form-group'>
        <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
            <div class='form-check'>
                <%= tag.label class: 'form-check-label' do %>
                    <%= check_box_tag 'your_checkbox' %>
                    <%= tag.text %>
                <% end %>
            </div>
        <% end %>
    </div>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title, :size => 140 %>
  </div>
   <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>
  <%= f.submit "Tweetする" %>
<% end %>
<%= link_to "Tweet一覧に戻る", hellos_path %>

app/views/hellos/show.html.erb
<h1>趣味について</h1>
<h3>Tweet詳細</h3>
<div class="hello">
  <p><%= @hello.title %></p>
  <p><%= @hello.created_at %></p>
</div>
<% @hello.tags.each do |tag| %>
    <span><%= tag.name %></span>
<% end %>

<%= link_to "Tweet一覧に戻る", hellos_path %>

app/views/layouts/application.html.erb
<html>
  <head>
    <title>Kounenki</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
     <script src="https://kit.fontawesome.com/ed533c4393.js" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <h1>Kounenki</h1>
      <div class="header-list">
      <ul>
        <li><%= link_to "TOP", tweets_top_path %></li>
        <li><%= link_to "新規投稿",new_tweet_path %></li>
          <li><%= link_to "診断", perfumes_path %></li>
         <li><%= link_to "ログイン",user_session_url %></li>
         
      </ul>
      </div>
    </header>
    <main>
      <%= yield %>
    </main>
    <footer>
      <p>Copyright © GeekSalon All Rights Reserved.</p>
    </footer>
  </body>
</html>

app/views/perfumes/index.html.erb
<!DOCTYPE html> 
<html lang="ja">
    <head>
        <meta charset="utf-8">
        <title>更年期診断スタート</title><!--ブラウザのタブのタイトルを指定-->
    </head>

    <body>
        <header>
            <h2s
             class="headline">
            <a>Perfu_me</a>
            </h2>
            <ul class="nav-list">
                <li class="nav-list-item">about fragrance</li>
                <li class="nav-list-item"><%= link_to "診断", perfumes_path, class: "link" %></li>
            </ul>
        </header>
 
        <div class="start">
            <h6>Are you ready?</h6>
            <%= link_to "診断を始める", new_perfume_path, class: "link" %>
        </div>
    </body>

app/views/perfumes/new.html.erb
  <%= form_tag(perfumes_path, method: :get) do%>
    <h3>Q.1 顔がほてる</h3>
        <label>
            <%= radio_button_tag :age, 0 %> いいえ
        </label>
        <label>
            <%= radio_button_tag :age, 1 %> はい
        </label>
    

    <h3>Q.2 汗をかきやすい</h3>
        <label>
            <%= radio_button_tag :sex, 0 %> いいえ
        </label>
        <label>
            <%= radio_button_tag :sex, 1 %> はい
        </label>

    <h3>Q.3 腰や手足が冷えやすい</h3>
        <label>
            <%= radio_button_tag :glasses, 0 %> いいえ
        </label>
        <label>
            <%= radio_button_tag :glasses, 1 %> はい
        </label>

     <h3>Q.4 息切れ、動悸がする</h3>
        <label> 
            <%= radio_button_tag :paper, 0 %>いいえ
        </label>
        <label>
            <%= radio_button_tag :paper, 1 %> はい
        </label>

    <h3>Q.5 寝つきが悪い、眠りが浅い</h3>
        <label>
            <%= radio_button_tag :sleep, 0 %> いいえ
        </label>
        <label>
            <%= radio_button_tag :sleep, 1 %> はい
        </label>

    <h3>Q.6 怒りやすく、イライラする</h3>
        <label>
            <%= radio_button_tag :angry, 0 %> いいえ
        </label>
        <label>
            <%= radio_button_tag :angry, 1 %> はい
        </label>
     
    <h3>Q.7 くよくよしたり、憂うつになる</h3>
        <label>
            <%= radio_button_tag :down, 0 %> いいえ
        </label>
        <label>
            <%= radio_button_tag :down, 1 %> はい
        </label>

    <h3>Q.8 頭痛、めまい、吐き気がよくある</h3>
        <label>
            <%= radio_button_tag :eye, 0 %> いいえ
        </label>
        <label>
            <%= radio_button_tag :eye, 1 %> はい
        </label>

    <h3>Q.9 疲れやすい</h3>
        <label>
            <%= radio_button_tag :tired, 0 %> いいえ
        </label>
        <label>
            <%= radio_button_tag :tired, 1 %> はい
        </label>

    <h3>Q.10 肩こり、腰痛、手足の痛みがある</h3>
        <label>
            <%= radio_button_tag :hand, 0 %> いいえ
        </label>
        <label>
            <%= radio_button_tag :hand, 1 %> はい
        </label>
    <br>

    <%= submit_tag '診断する'  %>
 </div>
 <% end %> 

app/views/perfumes/show.html.erb
<% @perfumes.each do |t| %>
    <% if t.number == @result %>
        <div class="tweet">
            あなたは<%= t.content %>です。
        </div>
    <% end %>
<% end %>

app/views/tweets/edit.html.erb
<%= form_for @tweet do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, :size => 140 %> 
  <%= f.submit "編集する" %>
<% end %>

app/views/tweets/index.html.erb
<h3 class="toukou">投稿一覧</h3>
<%= button_to 'ログアウト', destroy_user_session_path, method: :delete %>
<div class="container">
 <div class="kennsaku">
  
<h3>投稿を検索</h3>
 <%= form_tag({controller:"tweets",action:"index"}, method: :get) do %>
   <%= text_field_tag :search, params[:search] %>
   <%= submit_tag '検索する'  %>
 <% end %>

 <%= link_to "新規投稿へ", new_tweet_path %>
 </div>

<div class="itiran">
<h3>一覧ページ</h3>
<% if user_signed_in? %>
  <%= link_to "マイページへ", user_path(current_user.id) %>
<% end %>
<%= link_to "新規投稿ページへ", new_tweet_path %>
<div class="tweets-container">
  <% @tweets.each do |t| %>
    <div class="tweet">
       <%= t.user.email %>
      
      <div class="main-box">
        <div class="left-container"><%= t.title %></div>
        <div class="right-container">
       <%= link_to "詳細へ", tweet_path(t.id) %>
      <%= link_to "編集する", edit_tweet_path(t.id) %>
      <%= button_to "削除する", tweet_path(t.id), method: :delete %> 
    </div>
    </div>
        <p class="time"><%= t.created_at %></p>
   
      
       <% if user_signed_in? && current_user.id == t.user_id %>
      <% if current_user.already_liked?(t) %>
          <%= link_to tweet_like_path(id: t.id, tweet_id: t.id), method: :delete do %>
              <i class="fa-regular fa-heart"></i><%= t.likes.count %>
          <% end %>
      <% else %>
          <%= link_to tweet_likes_path(id: t.id, tweet_id: t.id), method: :post do %>
              <i class="fa-regular fa-heart"></i><%= t.likes.count %>
          <% end %>
      <% end %>
  <% else %>
      <i class="fa-regular fa-heart"></i><%= t.likes.count %>
  <% end %>
      <%= t.created_at %>
      <%# <% <% if t.image.attached? %>
      <%# <% <%= image_tag t.image_url, size: "250x200" if t.image? %>   
        <%# <% <%= image_tag t.image, size: '250x200' %> 
      <%# <% <% end  %> 
       </div>
      <% end %>
       </div>
      
      <%= stylesheet_link_tag 'index', :media => "all" %>
</div>
</div>

app/views/tweets/new.html.erb
<h3 class="toukou">新規投稿</h3>
<%= form_for @tweet do |f| %>
  <div class="field">
    <%= stylesheet_link_tag 'new', :media => "all" %>

<div class="post-container">
  
    <p class="title">投稿フォーム</p>
    <%= form_for(@tweet, :url => { controller:'tweets', action:'create'})do |f| %>
    <%= f.label :投稿内容 %>
        <br>
        <%= f.text_field :title,size: 40%>

        <br>
        <div class="form-check form-check-inline"> 
   <%= f.radio_button :release, '1' ,class:"form-check-input mb-3" %>
   <%= f.label :release, '公開', value: 1 %>
 </div>
 <div class="form-check form-check-inline">
   <%= f.radio_button :release, '0',class:"form-check-input mb-4" %>
   <%= f.label :release, '非公開', value: 0 %>
 </div>
  </div>
    <div class='form-group'>
        <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
            <div class='form-check'>
                <%= tag.label class: 'form-check-label' do %>
                  <%= tag.check_box class: 'form-check-input' %> 
                    <%= tag.text %>
                <% end %>
           </div>
         <% end %>
    </div>
    
<% end %> 


    

<%= form_tag({controller:"tweets",action:"new"}, method: :get) do %>
    <%= text_field_tag :tag %>
    <%= submit_tag 'タグを追加' %>
<% end %>
        <div class="field">
    <%= f.label :image %> 
    <p><%= f.file_field :image %></p> 
</div>
    <%= f.submit "送信"%>
    <br>
    <% end %>
</div>
    <%# <%= f.label :症状について %>
    
    

  

<%# <%= f.submit "投稿する" %> 
  
<%= link_to "Tweet一覧に戻る", tweets_path %>

app/views/tweets/show.html.erb
<h1>GeekTwitter</h1>
<h3>Tweet詳細</h3>
<div class="tweet">
  <p><%= @tweet.title %></p>
  <p><%= @tweet.created_at %></p>
  <% @tweet.tags.each do |tag| %>
    <span><%= tag.name %></span>
<% end %>
</div>
  <% if user_signed_in? %>
      <% if current_user.already_liked?(@tweet) %>
        <%= link_to tweet_like_path(@tweet), method: :delete do %>
        <i class="fa-regular fa-heart"></i><%= @tweet.likes.count %> 
        <% end %>
      <% else %>
        <%= link_to tweet_likes_path(@tweet), method: :post do %>
          <i class="fa-regular fa-heart"></i><%= @tweet.likes.count %>
        <% end %>
      <% end %>
    <% else %>
      <p>いいねの数 = </p><%= @tweet.likes.count %>
    <% end %>
  <%= link_to "編集する", edit_tweet_path(@tweet.id) %>
</div>

<h2>いいねしたユーザー</h2>
<% @tweet.liked_users.each do |user| %>
  <li><%= user.email %></li>
<% end %>

<%if current_user.id == @user.id %>
<% @user.tweets.each do |t| %>
        <%= t.title %>
        <%= t.body %>
    <% end %>
<% else %>
    <% @user.tweets.where(release:1).each do |t| %>
        <%= t.title %>
        <%= t.body %>
     <% end %>
<% end %>

<%= link_to "Tweet一覧に戻る", tweets_path %>

app/views/tweets/top.html.erb
<!DOCTYPE html> 
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" type="text/css" href="stylesheets/top.css">
 <body>
 

  
  
<div class="first-block">
  <section id="first-block">
    <div class="title-container">
      <h1>山田 太郎</h1>
      <h3>~ Geeksalon Webコース1期生 ~</h3>
    </div>

 </section>
  
  
  <div class="second-block">
   <p class="title">
      更年期とは……
    </p>
    <div class="about-container">
      <p class="text">
        <b>閉経を挟んだ前後約10年間のことを「更年期」と呼びます。</b>
          <br>この期間に現れるホットフラシュや気分の落ち込み、めまい、動悸といった症状でほかに原因となる病気の見つからないものを更年期症状といい、
        　<br>それらの症状によって日常生活に支障が出る場合に更年期障害と診断されます。
        </span>
       </p>
      
      

  </div>
  <div class="third-block">
    <section id="third-block">
    <p class="info-title">
       Features of this site
    </p>
    <div class="about-container">
      <p class="info-text">
        <b>投稿機能</b>
        <br>
        <span class="font-small">
        自分で投稿できる！
        <br>
        非公開にもできるので、
         <br>
         記録用に投稿することもできます。
        </span>
      </p>

      <p class="info-text">
        <b>検索機能</b>
        <br>
        <span class="font-small">
        いろんな人の投稿を閲覧することができます！
        <br>
        タグ検索があるので、
        <br>
        簡単に検索することができます。
        </span>
      </p>

      <p class="info-text">
        <b>診断機能</b>
        <br>
        <span class="font-small">
       更年期のセルフチェックを行えます。
        <br>
        簡単に診断可能で、
         <br>
         点数に応じてアドバイスもついています！
        <br>
        <%= link_to "診断はこちら", perfumes_path %>
       </span>
      </p>
 

       
      

  </div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<h3 class="toukou">マイページ</h3>
<h2>ユーザー情報</h2>
<p>名前 : <%= @user.name %></p>
<p>メールアドレス : <%= @user.email %></p>
<p>プロフィール : <%= @user.profile %></p>

<% if current_user.id == @user.id %>
  <%= link_to "編集する", edit_user_registration_path %>
<% end %>

<h2>ユーザーの投稿一覧</h2>
<% @user.tweets.each do |t| %>
  <%= t.user.name %>
  <%= t.title %>
<% end %>

<h2>ユーザーがいいねした投稿一覧</h2>
<% @user.liked_tweets.each do |t| %>
  <%= t.user.name %>
  <%= t.title %>
<% end %>

<%= link_to "Tweet一覧に戻る", tweets_path %>